
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

# Añadir nuestra configuración
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Render detecta el servidor en este puerto
EXPOSE 10000

CMD ["nginx", "-g", "daemon off;"]
