trigger:
- development 

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Path_back  

steps:
- script: |
    git config --global user.name "CopiaSeguridad"
    git config --global user.email "proyecto.integrado.iso@gmail.com"
  displayName: 'Configurar Git'

- script: |
    git clone https://$(GITHUB_PAT)@github.com/SantiagoSanchez-CeleminArevalo/Copia_seguridad_EsiMediaG03.git backup-repo
  displayName: 'Clonar repositorio de backup'
  env:
    GITHUB_PAT: $(GITHUB_PAT)

- script: |
    rsync -av $(Build.SourcesDirectory)/ backup-repo/
  displayName: 'Copiar todo el repositorio al backup'

- script: |
    cd backup-repo
    git checkout -B development
    git add .
    git diff-index --quiet HEAD || git commit -m "Backup automático $(Build.BuildId)"
    git push -u origin development
  displayName: 'Commit y push al repositorio de backup'
  env:
    GITHUB_PAT: $(GITHUB_PAT)
