FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copiamos todo el repo
COPY . .

# Compilamos SOLO el módulo usersbe (+ dependencias) 
RUN mvn -pl usersbe -am clean package -DskipTests

# Imagen final
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copiamos el jar de usersbe
COPY --from=build /app/usersbe/target/*.jar app.jar

# Render te inyecta PORT, así que lo respetamos
ENV PORT=8080
EXPOSE 8080

CMD ["java", "-jar", "app.jar", "--server.port=${PORT}"]
