FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

COPY . .

# Compilamos SOLO el módulo de contenidos
RUN mvn -pl EsiMediaContenidosG03 -am clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY --from=build /app/EsiMediaContenidosG03/target/*.jar app.jar

ENV PORT=8080
EXPOSE 8080

CMD ["java", "-jar", "app.jar", "--server.port=${PORT}"]
